### ISSUE TITLE
Nette 2.4. and PHP 5.6. compatibility

### ISSUE THREAD

**Issue by miloslavkostir** [contributte/nette-menu#37]
Hi,

can you create branches 1.0.x, 1.1.x and **1.2.x**?

1.0.x for PHP 5.6. and Nette 2.1.
1.1.x for PHP 5.6. and Nette 2.2. - 2.3.
**1.2.x for PHP 5.6. and Nette 2.4**

The Problem is with **PHP 5.6. and Nette 2.4.** - composer installs carrooi/nette-menu v1.1.1 but there are deprecated errors from Nette 2.4. Old version(s) above should be only for fix (deprecated) errors. I can fix these errors and make pull request from my fork. Just create branches.

Thanx
Milda

**Comment by foxycode** [comment]
@miloslavkostir PHP 5.6 is not supported version any more. Hope you don't need it these days.
