### ISSUE TITLE
v2.1.1

### ISSUE THREAD

**Issue by martenb** [contributte/nette-menu#40]
Hi,
could you please release version 2.1.1 for commit 5e8d009dba37b18651122251d30f82ad0ddbc298

Thanks

**Comment by foxycode** [comment]
@martenb Done

**Comment by martenb** [comment]
@foxycode don't see it in packagist https://packagist.org/packages/carrooi/nette-menu

**Comment by foxycode** [comment]
@martenb I don't have control over Carrooi packages. Watch discussion here https://github.com/contributte/nette-menu/issues/41 and after it will be resolved, new package under Contributte will be created.

**Comment by martenb** [comment]
@foxycode ok, thanks update.
